// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: jolt/plugins/remote_execution/worker.proto

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Worker_GetInstructions_FullMethodName = "/Worker/GetInstructions"
	Worker_GetTasks_FullMethodName        = "/Worker/GetTasks"
)

// WorkerClient is the client API for Worker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkerClient interface {
	// Called by a worker to get build instructions.
	GetInstructions(ctx context.Context, opts ...grpc.CallOption) (Worker_GetInstructionsClient, error)
	// Called by an executor (Jolt client) to get task execution requests.
	// Task updates, including status and logs are sent back to the scheduler.
	GetTasks(ctx context.Context, opts ...grpc.CallOption) (Worker_GetTasksClient, error)
}

type workerClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerClient(cc grpc.ClientConnInterface) WorkerClient {
	return &workerClient{cc}
}

func (c *workerClient) GetInstructions(ctx context.Context, opts ...grpc.CallOption) (Worker_GetInstructionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[0], Worker_GetInstructions_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerGetInstructionsClient{stream}
	return x, nil
}

type Worker_GetInstructionsClient interface {
	Send(*WorkerUpdate) error
	Recv() (*WorkerRequest, error)
	grpc.ClientStream
}

type workerGetInstructionsClient struct {
	grpc.ClientStream
}

func (x *workerGetInstructionsClient) Send(m *WorkerUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerGetInstructionsClient) Recv() (*WorkerRequest, error) {
	m := new(WorkerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *workerClient) GetTasks(ctx context.Context, opts ...grpc.CallOption) (Worker_GetTasksClient, error) {
	stream, err := c.cc.NewStream(ctx, &Worker_ServiceDesc.Streams[1], Worker_GetTasks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &workerGetTasksClient{stream}
	return x, nil
}

type Worker_GetTasksClient interface {
	Send(*TaskUpdate) error
	Recv() (*TaskRequest, error)
	grpc.ClientStream
}

type workerGetTasksClient struct {
	grpc.ClientStream
}

func (x *workerGetTasksClient) Send(m *TaskUpdate) error {
	return x.ClientStream.SendMsg(m)
}

func (x *workerGetTasksClient) Recv() (*TaskRequest, error) {
	m := new(TaskRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WorkerServer is the server API for Worker service.
// All implementations must embed UnimplementedWorkerServer
// for forward compatibility
type WorkerServer interface {
	// Called by a worker to get build instructions.
	GetInstructions(Worker_GetInstructionsServer) error
	// Called by an executor (Jolt client) to get task execution requests.
	// Task updates, including status and logs are sent back to the scheduler.
	GetTasks(Worker_GetTasksServer) error
	mustEmbedUnimplementedWorkerServer()
}

// UnimplementedWorkerServer must be embedded to have forward compatible implementations.
type UnimplementedWorkerServer struct {
}

func (UnimplementedWorkerServer) GetInstructions(Worker_GetInstructionsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetInstructions not implemented")
}
func (UnimplementedWorkerServer) GetTasks(Worker_GetTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method GetTasks not implemented")
}
func (UnimplementedWorkerServer) mustEmbedUnimplementedWorkerServer() {}

// UnsafeWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServer will
// result in compilation errors.
type UnsafeWorkerServer interface {
	mustEmbedUnimplementedWorkerServer()
}

func RegisterWorkerServer(s grpc.ServiceRegistrar, srv WorkerServer) {
	s.RegisterService(&Worker_ServiceDesc, srv)
}

func _Worker_GetInstructions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).GetInstructions(&workerGetInstructionsServer{stream})
}

type Worker_GetInstructionsServer interface {
	Send(*WorkerRequest) error
	Recv() (*WorkerUpdate, error)
	grpc.ServerStream
}

type workerGetInstructionsServer struct {
	grpc.ServerStream
}

func (x *workerGetInstructionsServer) Send(m *WorkerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerGetInstructionsServer) Recv() (*WorkerUpdate, error) {
	m := new(WorkerUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Worker_GetTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WorkerServer).GetTasks(&workerGetTasksServer{stream})
}

type Worker_GetTasksServer interface {
	Send(*TaskRequest) error
	Recv() (*TaskUpdate, error)
	grpc.ServerStream
}

type workerGetTasksServer struct {
	grpc.ServerStream
}

func (x *workerGetTasksServer) Send(m *TaskRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *workerGetTasksServer) Recv() (*TaskUpdate, error) {
	m := new(TaskUpdate)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Worker_ServiceDesc is the grpc.ServiceDesc for Worker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Worker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Worker",
	HandlerType: (*WorkerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInstructions",
			Handler:       _Worker_GetInstructions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetTasks",
			Handler:       _Worker_GetTasks_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "jolt/plugins/remote_execution/worker.proto",
}
