version: "3.5"
services:
  amqp:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  cache:
    image: nginx:latest
    deploy:
      replicas: 1
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "8080:80"
    volumes:
      - cache-http:/usr/share/nginx/html
  dashboard:
    image: robrt/jolt-dashboard:latest
    ports:
      - "80:80"
  worker:
    image: robrt/jolt:latest
    deploy:
      replicas: 2
    command: ["-c", "/opt/jolt/worker.conf", "amqp-worker"]
    configs:
      - source: worker-amqp.conf
        target: /opt/jolt/worker.conf
    volumes:
      - cache-node:/root/.cache/jolt
configs:
  worker-amqp.conf:
    file: ./worker-amqp.conf
  nginx.conf:
    file: ./nginx.conf
volumes:
  cache-node:
  cache-http:
