FROM docker.io/golang:1.24-bookworm as base

FROM base as tools
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get -y upgrade

FROM tools as build
ARG BUILD_ARGS
ADD . /usr/src
WORKDIR /usr/src/services
RUN go build -ldflags '-s -w' ${BUILD_ARGS} ./cmd/cache

FROM docker.io/debian:bookworm-slim
COPY --from=build /usr/src/services/cache /opt/jolt/cache
RUN mkdir /data
WORKDIR /data
ENTRYPOINT ["/opt/jolt/cache"]
