FROM docker.io/rabbitmq:3.8

RUN mkdir -p $RABBITMQ_HOME/plugins && \
    cd $RABBITMQ_HOME/plugins && \
    apt-get update && apt-get install -y wget && \
    wget https://github.com/noxdafox/rabbitmq-message-deduplication/releases/download/0.4.3/rabbitmq_message_deduplication-v3.8.x-0.4.3.ez && \
    wget https://github.com/noxdafox/rabbitmq-message-deduplication/releases/download/0.4.3/elixir-1.8.2.ez && \
    rabbitmq-plugins enable rabbitmq_message_deduplication
