FROM python:3-buster

RUN apt-get update && apt-get install -y gcc g++ make libffi-dev musl-dev libssl-dev git ninja-build python3-pygit2
ADD . /opt/jolt
RUN pip3 install -e /opt/jolt
RUN pip3 install pika

ENV RABBITMQ_HOST=amqp-service
ENV RABBITMQ_PORT=5672
WORKDIR /tmp/jolt-workspace
CMD ["jolt", "-c", "/opt/jolt/docker/rabbitmq.conf", "amqp-worker"]
