FROM docker.io/golang:1.24-bookworm as base

FROM base as tools
ARG DEBIAN_FRONTEND=noninteractive
ARG BLAKE3_VERSION=1.8.3
RUN apt-get update && apt-get -y upgrade && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*
RUN git clone https://github.com/BLAKE3-team/BLAKE3.git /blake3
RUN mkdir -p /blake3/build && cd /blake3/build && git checkout ${BLAKE3_VERSION} && cmake ../c -DCMAKE_INSTALL_PREFIX=/usr && make && make install && rm -rf /blake3

FROM tools as build
ARG BUILD_ARGS
ADD . /usr/src
WORKDIR /usr/src/services
RUN go build -ldflags '-s -w' ${BUILD_ARGS} ./cmd/cache

FROM docker.io/debian:bookworm-slim
COPY --from=build /usr/src/services/cache /opt/jolt/cache
RUN mkdir /data
WORKDIR /data
ENTRYPOINT ["/opt/jolt/cache"]
