FROM docker.io/python:3.11-slim
RUN apt-get update && apt-get install -y build-essential git make ninja-build

COPY . /opt/jolt
RUN pip3 install -e /opt/jolt[allure]
ENTRYPOINT ["jolt"]
CMD []

RUN mkdir /ws
WORKDIR /ws
