FROM python:3.7-alpine

RUN apk update && apk add gcc g++ make libffi-dev musl-dev openssl-dev git ninja
ADD . /opt/jolt
RUN pip3 install -e /opt/jolt
RUN pip3 install pika

ENV RABBITMQ_HOST=amqp-service
ENV RABBITMQ_PORT=5672
WORKDIR /tmp/jolt-workspace
CMD ["jolt", "-c", "/opt/jolt/docker/rabbitmq.conf", "amqp-worker"]
