# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from jolt.plugins.remote_execution import log_pb2 as jolt_dot_plugins_dot_remote__execution_dot_log__pb2


class LogStashStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadLog = channel.unary_stream(
                '/LogStash/ReadLog',
                request_serializer=jolt_dot_plugins_dot_remote__execution_dot_log__pb2.ReadLogRequest.SerializeToString,
                response_deserializer=jolt_dot_plugins_dot_remote__execution_dot_log__pb2.ReadLogResponse.FromString,
                )


class LogStashServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadLog(self, request, context):
        """Read a log file.
        Log lines are streamed back as they are read from internal storage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogStashServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadLog': grpc.unary_stream_rpc_method_handler(
                    servicer.ReadLog,
                    request_deserializer=jolt_dot_plugins_dot_remote__execution_dot_log__pb2.ReadLogRequest.FromString,
                    response_serializer=jolt_dot_plugins_dot_remote__execution_dot_log__pb2.ReadLogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LogStash', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LogStash(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/LogStash/ReadLog',
            jolt_dot_plugins_dot_remote__execution_dot_log__pb2.ReadLogRequest.SerializeToString,
            jolt_dot_plugins_dot_remote__execution_dot_log__pb2.ReadLogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
