title Uncached Local Build - With Network Cache

User->Jolt: "build example"
Jolt->Jolt: Build Directed Asyclic Graph
Jolt->Jolt: Calculate Task Identity
Jolt->Local Cache: Lookup Task Artifact
Local Cache->Jolt: Not Found
Jolt->Network Cache: Lookup Task Artifact
Network Cache->Jolt: Not Found
Jolt->Jolt: Execute Task
Jolt->Local Cache: Commit Task Artifact
Local Cache->Jolt: Ok
Jolt->Jolt: Compress Archive
Jolt->Network Cache: Upload Archive
Network Cache->Jolt: Ok
Jolt->User: Done
