// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: jolt/plugins/remote_execution/worker.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerRequest_Action int32

const (
	// Deploy and start executor.
	WorkerRequest_BUILD WorkerRequest_Action = 0
	// Cancel build gracefully.
	// Sends interrupt signal to executor.
	WorkerRequest_CANCEL_BUILD WorkerRequest_Action = 1
	// Terminate executor.
	WorkerRequest_TERMINATE WorkerRequest_Action = 2
)

// Enum value maps for WorkerRequest_Action.
var (
	WorkerRequest_Action_name = map[int32]string{
		0: "BUILD",
		1: "CANCEL_BUILD",
		2: "TERMINATE",
	}
	WorkerRequest_Action_value = map[string]int32{
		"BUILD":        0,
		"CANCEL_BUILD": 1,
		"TERMINATE":    2,
	}
)

func (x WorkerRequest_Action) Enum() *WorkerRequest_Action {
	p := new(WorkerRequest_Action)
	*p = x
	return p
}

func (x WorkerRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_jolt_plugins_remote_execution_worker_proto_enumTypes[0].Descriptor()
}

func (WorkerRequest_Action) Type() protoreflect.EnumType {
	return &file_jolt_plugins_remote_execution_worker_proto_enumTypes[0]
}

func (x WorkerRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerRequest_Action.Descriptor instead.
func (WorkerRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_jolt_plugins_remote_execution_worker_proto_rawDescGZIP(), []int{0, 0}
}

type WorkerUpdate_Status int32

const (
	// The worker is coming online and
	// registers itself to receive tasks.
	WorkerUpdate_ENLISTING WorkerUpdate_Status = 0
	// The worker is going offline.
	WorkerUpdate_DELISTING WorkerUpdate_Status = 1
	// The build executor process has terminated gracefully.
	WorkerUpdate_BUILD_ENDED WorkerUpdate_Status = 2
	// The build executor could not be installed.
	// Typically means that pip install has failed.
	WorkerUpdate_DEPLOY_FAILED WorkerUpdate_Status = 3
	// The build executor terminated with non-zero exit status.
	WorkerUpdate_EXECUTOR_FAILED WorkerUpdate_Status = 4
)

// Enum value maps for WorkerUpdate_Status.
var (
	WorkerUpdate_Status_name = map[int32]string{
		0: "ENLISTING",
		1: "DELISTING",
		2: "BUILD_ENDED",
		3: "DEPLOY_FAILED",
		4: "EXECUTOR_FAILED",
	}
	WorkerUpdate_Status_value = map[string]int32{
		"ENLISTING":       0,
		"DELISTING":       1,
		"BUILD_ENDED":     2,
		"DEPLOY_FAILED":   3,
		"EXECUTOR_FAILED": 4,
	}
)

func (x WorkerUpdate_Status) Enum() *WorkerUpdate_Status {
	p := new(WorkerUpdate_Status)
	*p = x
	return p
}

func (x WorkerUpdate_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerUpdate_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_jolt_plugins_remote_execution_worker_proto_enumTypes[1].Descriptor()
}

func (WorkerUpdate_Status) Type() protoreflect.EnumType {
	return &file_jolt_plugins_remote_execution_worker_proto_enumTypes[1]
}

func (x WorkerUpdate_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerUpdate_Status.Descriptor instead.
func (WorkerUpdate_Status) EnumDescriptor() ([]byte, []int) {
	return file_jolt_plugins_remote_execution_worker_proto_rawDescGZIP(), []int{1, 0}
}

// Requests sent from scheduler to workers
type WorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The worker action requested by the scheduler.
	Action WorkerRequest_Action `protobuf:"varint,1,opt,name=action,proto3,enum=WorkerRequest_Action" json:"action,omitempty"`
	// The build that is concerned.
	Build *BuildRequest `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	// Id of the worker to which this is sent
	WorkerId string `protobuf:"bytes,3,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	// Id of the build that is concerned
	BuildId string `protobuf:"bytes,4,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
}

func (x *WorkerRequest) Reset() {
	*x = WorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jolt_plugins_remote_execution_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRequest) ProtoMessage() {}

func (x *WorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_jolt_plugins_remote_execution_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRequest.ProtoReflect.Descriptor instead.
func (*WorkerRequest) Descriptor() ([]byte, []int) {
	return file_jolt_plugins_remote_execution_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRequest) GetAction() WorkerRequest_Action {
	if x != nil {
		return x.Action
	}
	return WorkerRequest_BUILD
}

func (x *WorkerRequest) GetBuild() *BuildRequest {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *WorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRequest) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

// Updates sent from workers to scheduler
type WorkerUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Current status of the worker.
	Status WorkerUpdate_Status `protobuf:"varint,1,opt,name=status,proto3,enum=WorkerUpdate_Status" json:"status,omitempty"`
	// The worker's platform properties.
	// These properties are used by the scheduler to select
	// tasks that are compatible with this worker, e.g.
	// node.os == Linux, node.arch == arm, etc.
	Platform *Platform `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// Failure details
	Error *WorkerError `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WorkerUpdate) Reset() {
	*x = WorkerUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jolt_plugins_remote_execution_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerUpdate) ProtoMessage() {}

func (x *WorkerUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_jolt_plugins_remote_execution_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerUpdate.ProtoReflect.Descriptor instead.
func (*WorkerUpdate) Descriptor() ([]byte, []int) {
	return file_jolt_plugins_remote_execution_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerUpdate) GetStatus() WorkerUpdate_Status {
	if x != nil {
		return x.Status
	}
	return WorkerUpdate_ENLISTING
}

func (x *WorkerUpdate) GetPlatform() *Platform {
	if x != nil {
		return x.Platform
	}
	return nil
}

func (x *WorkerUpdate) GetError() *WorkerError {
	if x != nil {
		return x.Error
	}
	return nil
}

// Representation of a worker error
type WorkerError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Short error message
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// Error details, such as logs or callstack
	Details string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
}

func (x *WorkerError) Reset() {
	*x = WorkerError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_jolt_plugins_remote_execution_worker_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerError) ProtoMessage() {}

func (x *WorkerError) ProtoReflect() protoreflect.Message {
	mi := &file_jolt_plugins_remote_execution_worker_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerError.ProtoReflect.Descriptor instead.
func (*WorkerError) Descriptor() ([]byte, []int) {
	return file_jolt_plugins_remote_execution_worker_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkerError) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_jolt_plugins_remote_execution_worker_proto protoreflect.FileDescriptor

var file_jolt_plugins_remote_execution_worker_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x6a, 0x6f, 0x6c, 0x74, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x72,
	0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x6a, 0x6f,
	0x6c, 0x74, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x2d, 0x6a, 0x6f, 0x6c, 0x74, 0x2f, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x73, 0x2f, 0x72, 0x65,
	0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x73,
	0x63, 0x68, 0x65, 0x64, 0x75, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd1,
	0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x2d, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x15, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x23, 0x0a, 0x05, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x05, 0x62,
	0x75, 0x69, 0x6c, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x49, 0x64, 0x22, 0x34, 0x0a, 0x06,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c, 0x5f, 0x42, 0x55, 0x49, 0x4c,
	0x44, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45,
	0x10, 0x02, 0x22, 0xe8, 0x01, 0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x25, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x22, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x5f, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x45, 0x4e, 0x4c, 0x49, 0x53, 0x54,
	0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x49,
	0x4e, 0x47, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x42, 0x55, 0x49, 0x4c, 0x44, 0x5f, 0x45, 0x4e,
	0x44, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x44, 0x45, 0x50, 0x4c, 0x4f, 0x59, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x45, 0x58, 0x45, 0x43,
	0x55, 0x54, 0x4f, 0x52, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x04, 0x22, 0x41, 0x0a,
	0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73,
	0x32, 0x69, 0x0a, 0x06, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x49, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x0d, 0x2e,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0e, 0x2e, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x29, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x12, 0x0b, 0x2e, 0x54,
	0x61, 0x73, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x0c, 0x2e, 0x54, 0x61, 0x73, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0e, 0x5a, 0x0c, 0x70,
	0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_jolt_plugins_remote_execution_worker_proto_rawDescOnce sync.Once
	file_jolt_plugins_remote_execution_worker_proto_rawDescData = file_jolt_plugins_remote_execution_worker_proto_rawDesc
)

func file_jolt_plugins_remote_execution_worker_proto_rawDescGZIP() []byte {
	file_jolt_plugins_remote_execution_worker_proto_rawDescOnce.Do(func() {
		file_jolt_plugins_remote_execution_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_jolt_plugins_remote_execution_worker_proto_rawDescData)
	})
	return file_jolt_plugins_remote_execution_worker_proto_rawDescData
}

var file_jolt_plugins_remote_execution_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_jolt_plugins_remote_execution_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_jolt_plugins_remote_execution_worker_proto_goTypes = []interface{}{
	(WorkerRequest_Action)(0), // 0: WorkerRequest.Action
	(WorkerUpdate_Status)(0),  // 1: WorkerUpdate.Status
	(*WorkerRequest)(nil),     // 2: WorkerRequest
	(*WorkerUpdate)(nil),      // 3: WorkerUpdate
	(*WorkerError)(nil),       // 4: WorkerError
	(*BuildRequest)(nil),      // 5: BuildRequest
	(*Platform)(nil),          // 6: Platform
	(*TaskUpdate)(nil),        // 7: TaskUpdate
	(*TaskRequest)(nil),       // 8: TaskRequest
}
var file_jolt_plugins_remote_execution_worker_proto_depIdxs = []int32{
	0, // 0: WorkerRequest.action:type_name -> WorkerRequest.Action
	5, // 1: WorkerRequest.build:type_name -> BuildRequest
	1, // 2: WorkerUpdate.status:type_name -> WorkerUpdate.Status
	6, // 3: WorkerUpdate.platform:type_name -> Platform
	4, // 4: WorkerUpdate.error:type_name -> WorkerError
	3, // 5: Worker.GetInstructions:input_type -> WorkerUpdate
	7, // 6: Worker.GetTasks:input_type -> TaskUpdate
	2, // 7: Worker.GetInstructions:output_type -> WorkerRequest
	8, // 8: Worker.GetTasks:output_type -> TaskRequest
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_jolt_plugins_remote_execution_worker_proto_init() }
func file_jolt_plugins_remote_execution_worker_proto_init() {
	if File_jolt_plugins_remote_execution_worker_proto != nil {
		return
	}
	file_jolt_common_proto_init()
	file_jolt_plugins_remote_execution_scheduler_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_jolt_plugins_remote_execution_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jolt_plugins_remote_execution_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_jolt_plugins_remote_execution_worker_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_jolt_plugins_remote_execution_worker_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_jolt_plugins_remote_execution_worker_proto_goTypes,
		DependencyIndexes: file_jolt_plugins_remote_execution_worker_proto_depIdxs,
		EnumInfos:         file_jolt_plugins_remote_execution_worker_proto_enumTypes,
		MessageInfos:      file_jolt_plugins_remote_execution_worker_proto_msgTypes,
	}.Build()
	File_jolt_plugins_remote_execution_worker_proto = out.File
	file_jolt_plugins_remote_execution_worker_proto_rawDesc = nil
	file_jolt_plugins_remote_execution_worker_proto_goTypes = nil
	file_jolt_plugins_remote_execution_worker_proto_depIdxs = nil
}
